### ISSUE TITLE
Exception in thread "main" java.lang.IllegalStateException: Resource '/mnist_png/training' cannot be found

### ISSUE THREAD

**Issue by germal** [PacktPublishing/Hands-On-Deep-Learning-with-Apache-Spark#2]
Hi Guglielmo

I am trying to execute the CNN example of the Chapter 4 .
I have downloaded the mnist file and unzipped under the directory /mnist_png/training but running the spark submit command I get the following error 

**Exception in thread "main" java.lang.IllegalStateException: Resource '/mnist_png/training' cannot be found** 

I used the following command to submit the job 

**spark-submit  --class org.googlielmo.cnnmnist.MnistClassifierWithUi  target/cnnmnist-1.0.jar  spark://osboxes:7077**

Could you please help me ? 
Thanks in advance for your support
Regards
Germal
![error](https://user-images.githubusercontent.com/47027729/52773100-6f984f80-303a-11e9-9e96-051c5af63054.png)

**Comment by virtualramblas** [comment]
Hi Germal,

I have noticed that you are trying to submit to Spark chapter 8's MnistClassifierWithUi class, which isn't a Spark application, but a standalone Java DL4J app to train a CNN model and use the DL4J UI in real time. No Spark example has been added to GitHub for chapter 8, as the one that has been presented in that chapter has been left to readers to implement, being the focus of the chapter on understanding how to monitor and get insights in real time about an ongoing training (with Spark or not).
That said, if you look at line 48 of the example, you can see that the training data set is expected in the application classpath. So you need to add it to your application classpath.

Best Regards,
Guglielmo

**Comment by germal** [comment]
Hi Guglielmo

Sorry for the delay in replying , in these days I faced a very tough situation.
I tried to add the /mnist_png/training to the classpath in the java execution command but the error is very similar  .
Could you please check ?
Thanks
Germal
![error 2](https://user-images.githubusercontent.com/47027729/52748113-f111c280-2fe5-11e9-83fa-150ff42e6b5c.png)

**Comment by germal** [comment]
Hi Guglielmo 
Searching a lot on google I found a modification to solve the issue 

![immagine](https://user-images.githubusercontent.com/47027729/52891547-f6a90d00-318b-11e9-85d0-880e525cbf81.png)

before but now there is another issue 

![error](https://user-images.githubusercontent.com/47027729/52891307-7b932700-318a-11e9-90f8-4a929415f4e1.jpg)
Please post the complete implementation and the commands to run the code in the book because it is not possible banging the head googling around to make the code working.
Regards

**Comment by virtualramblas** [comment]
Hi Germal,

First of all, please note that the implementation of this example is complete and has been tested by the Packt Publishing technical team before publishing the code to GitHub and the book. Your saying that the implementation isn't complete isn't true. That said, the readme file for this repo states that all the examples use Apache Maven and this example comes with a POM file, so the first thing I would have tried is going to the Maven documentation (if new to this tool) and use the Maven exec plugin (http://www.mojohaus.org/exec-maven-plugin/usage.html) before trying different ways. Did you try to run it this way?
On Linux Ububtu and Mac the way the Jar has been then packaged the error with the UI didn't happen. It would be good for others if you could share the steps you did to solve it in a separate thread in this repo. Thanks.
The last exception you shared doesn't depend on the way you run the example, but it could be related to the dataset location and/or original archive extraction. Could you please open a separate issue, detailing all of the steps you did (from dataset download until example execution), as it is a different matter from this and I am going to close this issue. Thanks.
Best Regards,
Guglielmo

**Comment by germal** [comment]
Hi Guglielmo,
As you know very well each code works under specific prerequisites.
The code attached doesn't work with the pom.xml attached to the book.
I am a Unix sysadmin/pentester not a Java programmer so I spent days to find the plugins that made the code working but I admit that it has been a good exercise.Here the plugin that I added in the  build section 

           <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>1.3.2</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <executable>java</executable>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>1.3.2</version>
                <configuration>
                    <shadedArtifactAttached>true</shadedArtifactAttached>
                    <shadedClassifierName>${shadedClassifier}</shadedClassifierName>
                    <createDependencyReducedPom>true</createDependencyReducedPom>
                    <filters>
                        <filter>
                            <artifact>*:*</artifact>
                            <excludes>
                                
                                <exclude>META-INF/*.SF</exclude>
                                <exclude>META-INF/*.DSA</exclude>
                                <exclude>META-INF/*.RSA</exclude>
                            </excludes>
                        </filter>
                    </filters>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>reference.conf</resource>
                                </transformer>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer" />
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>

Furthermore I found that the official MNIST link that you provided in the book (http://yann.lecun.com/exdb/mnist/) is not the exact source of the data that the code can process. Indeed one must download the data from another repository in order to allow the code to work ; this one https://github.com/myleott/mnist_png, where one can find the mnist database in png format.
Your book is really a good book with very intuitive explanations of complex algorithms and their implementation with Java and Spark, only, in my opinion, it needs of a git page that leads the students to run the examples attached.
I hope that this helps the students.
Regards
Germal
